packages:
  # Use Volto core packages and this addon package only
  - 'core/packages/*'
  - 'packages/volto-sustentare-tema'
  # Also include the inner volto-site-componentes package so workspace:* resolves locally
  - '../../volto-site-componentes/packages/volto-site-componentes'
  # Add local workspace package for the Google Analytics addon when pulled by mrs-developer
  - 'packages/volto-google-analytics'
